### ISSUE TITLE
Will SikuliX2 be pure Java? --- yes, but ...

### ISSUE THREAD

**Issue by jivank** [RaiMan/SikuliNG#13]
I remember reading somewhere that SikuliX2 will be in pure java (no dependencies on external non java libraries and programs). Will this still be the case?

**Comment by RaiMan** [comment]
Pure Java yes: but this is meant for the written code only

SikuliX's main features will always depend on OpenCV and Tesseract, which in turn are non-java packages available for Windows, Mac and Linux. 

For both packages there are JNI/JNA based wrappers available with a Java API to address the library features. OpenCV comes with its own Java interface solution. For Tesseract I will use Tess4J.

For special features as they are available in the App class I will use BridJ on Windows to access Windows API features, on Mac it is internal AppleScript and on Linux appropriate packages in a command line subprocess.

So yes, version 2 will be completely written in Java, but will rely on libraries not written in Java, that in turn have a Java wrapper available.

**Comment by Forgen** [comment]
How does this compare with SikuliX1? Does it have non-Java code?

**Comment by RaiMan** [comment]
@Forgen 

In SikuliX1 there is an additional C++ layer above the OpenCV and Tesseract libraries, that in turn is 
accessed via JNI from the Java level. As mentioned in the above comment: this will be completely moved to the Java level using Java/JNI wrappers.

Some minor C++ coding for the class App features will also be implemented at the Java level as mentioned above.

So for the SikuliX feature implementation it will be pure Java code.

To allow the usage in scripting environments (JavaScript, Python/Jython, Ruby/JRuby, ...) there might be small pieces needed to support scripting.

Come back if this does not answer your question.

**Comment by EducatedMF** [comment]
@RaiMan Can I use it native if I wanted to? In VisualStudio with only c++ ?

**Comment by RaiMan** [comment]
@EducatedMF 
SikuliX2 will be a pure Java related to the implementation of the features.

To use the features from C++ would only be possible by using JNI/JNA, which would be your own responsibility.
Or if there is some package available cplusplus-java like node-java for node.js

**Comment by RaiMan** [comment]
Everything will be Java only either by using existing Java layers (OpenCV, Tess4J, ...) or by using the JNA implementation java-native-access/jna to access native libraries (which usually have to be installed separately by the user
