### ISSUE TITLE
Love this project, how can I build/install it ?

### ISSUE THREAD

**Issue by medyagh** [RaiMan/SikuliNG#16]
Hi I love this project and also the name of it, really cute !
I like to be able to install and build it my local machine and hopefully maybe be able to contribute back to it.

I have mac 64bit and mvn 3.3.3
when I mvn install it I get these errors: 

```

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Forking command line: /bin/sh -c cd /Users/medya/workspace/dummy-projects/SikuliX2/sikulixcoretest && /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/bin/java -jar /Users/medya/workspace/dummy-projects/SikuliX2/sikulixcoretest/target/surefire/surefirebooter4564863574668949698.jar /Users/medya/workspace/dummy-projects/SikuliX2/sikulixcoretest/target/surefire/surefire1798097782650179290tmp /Users/medya/workspace/dummy-projects/SikuliX2/sikulixcoretest/target/surefire/surefire_06921974529382272115tmp
Running com.sikulix.sikulixcoretest.TestCoreBasic
SX.Log: getTranslation: missing ressource for SXGlobal
13:25:54 [main] INFO  TestCoreBasic -  0: result: test_00_play: nothing to do
13:25:54 [main] INFO  TestCoreBasic -  1: result: test_10_startup_workdir: /Users/medya/workspace/dummy-projects/SikuliX2/sikulixcoretest
*** classpath dump sikulix
  0: /Users/medya/workspace/dummy-projects/SikuliX2/sikulixcoretest/target/surefire/surefirebooter4564863574668949698.jar
*** classpath dump end
13:25:54 [main] INFO  SX.Global - *** terminating: exportNativeLibraries: libs not on classpath: /Native/mac

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] sikulix2 ........................................... SUCCESS [  0.185 s]
[INFO] sikulixapi ......................................... SUCCESS [  1.710 s]
[INFO] sikulix ............................................ SUCCESS [  0.372 s]
[INFO] sikulixcoretest .................................... FAILURE [  2.325 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.681 s
[INFO] Finished at: 2016-07-12T13:25:54-05:00
[INFO] Final Memory: 15M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project sikulixcoretest: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project sikulixcoretest: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: java.lang.RuntimeException: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
    at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.close(ForkClient.java:257)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:301)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:116)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:740)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAllProviders(AbstractSurefireMojo.java:682)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:648)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:586)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

```

**Comment by medyagh** [comment]
update I was able to mvn install it by skipping the test 
`mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`

now next step is figuring out how to run it.

**Comment by RaiMan** [comment]
Thanks for your interest.

As already mentioned in your other post #14:
Nothing to run yet - not usable currently for anything.

If you want to do something that helps:
Find out, why sikulixcoretest does not work in your situation.

I develop on Mac OSX 10.11 with Java 8 using IntelliJ IDEA CE.

**Comment by stheno** [comment]
I wasn't sure where to post this but I figure here is as good of a spot as any.
I created a Discord server chat room for all things SikuliX.
We have seen an exponential increase in community involvement in our projects by adding a discord chat for them. I am wondering if you would be interested in this sort of thing for your project(s) RaiMan?
If so I can post the instant invite link should you like the idea.

**Comment by DarrenGuinness** [comment]
RaiMan, when you say that it is not useable for anything yet do you mean the IDE or the sikulixapi.jar or both? I am using OSX and trying to run the 1.1 sikulixapi.jar which doesn't seem to have support for screen captures due to AWT issues. Is there any chance this build runs the API jar on OSX?

**Comment by RaiMan** [comment]
>  I am using OSX
Did you already try SikuliX version 1.1.1? Even works on Sierra and with Retina displays.

To answer your question:
version 2 is not useable yet for anything.

**Comment by DarrenGuinness** [comment]
The 1.1 IDE seems to run fine, but I am working on an application which is attempting to use the 1.1 sikulixapi.jar  library. Whenever I call screen based imports which use awt's BufferedImage class (screen, screenimage, etc) my application seems to hang.

**Comment by RaiMan** [comment]
@DarrenGuinness 
not sure what you are talking about:
> Whenever I call screen based imports ???
... my application seems to hang ???

please provide code samples and more information on the "hang symptoms".

**Comment by DarrenGuinness** [comment]
Turns out it was a node-java problem ( https://github.com/joeferner/node-java/issues/90 ). Sorry for the mistake.

**Comment by zutuanwang** [comment]
# buid failed!
-------------------------------------------------------------------------------------------------------------------
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ sikulixapi ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 112 source files to C:\Users\action\git\SikuliX2\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[44,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[46,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[51,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[56,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[61,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[66,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[162,11] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[168,11] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[189,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[209,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[235,10] method declaration is invalid; need return type
[INFO] 11 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.909 s
[INFO] Finished at: 2018-04-20T19:20:34+08:00
[INFO] Final Memory: 10M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project sikulixapi: Compilation failure: Compilation failure:
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[44,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[46,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[51,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[56,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[61,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/RegionE.java:[66,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[162,11] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[168,11] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[189,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[209,10] method declaration is invalid; need return type
[ERROR] /C:/Users/action/git/SikuliX2/src/main/java/org/sikuli/script/ScreenA.java:[235,10] method declaration is invalid; need return type
[ERROR] -> [Help 1]

**Comment by RaiMan** [comment]
@zutuanwang 
Sorry, but this is the current state. I am working on it.

**Comment by RaiMan** [comment]
project paused
