### ISSUE TITLE
Some assessment information

### ISSUE THREAD

**Issue by rocky4546** [RaiMan/SikuliNG#26]
I am using Sikuli 1.1 and wanted to give you some feedback.  The focus feature on windows does not allows work.  This is caused by MS Windows security.  There is a MS website that goes through when they allow for focus from an automated tool to take place.  I found the answer, but it is not easy.  To have guaranteed focus on MS Windows, you must use Visual Basic or the like (I use vbs).  You have to create a class file that uses MS Windows GetForegroundWindow, GetWindowText, GetWindowThreadProcessId, IsIconic methods.  Then create and register the DLL from the *.cls file using those functions.  I wrote a vbs script that passes the PID and is called from java.  What the vbs script does first is try the simple focus and see if that worked.  It that fails, then the trick is to iconize all other windows and then repeat focus on the window you want.  Once you restore the active windows, your window will now be in front.

I have also integrated Sikuli into the Selenium grid using the Selenium "extra" servlet point.  The integration worked extremely well.  I, in fact, also integrated PLink from PuTTY into that same grid point.  So now I have a terminal window that I know exactly what is in and out and do not have to OCR it.  To use the grid, I first initiate a Selenium session.  That session id is then used by the Sikuli grid to connect to the same node that Selenium is using.  This way, both Selenium and Sikuli are testing on the same node, which is a very important feature.

Keep up the great work!  It is very much appreciated.

**Comment by RaiMan** [comment]
Thanks for valuable information and feedback.

I would appreciate to get the sources of the above mentioned vbs stuff and the java snippet, that runs it. If you agree, just send it to my mail sikulix--at--outlook--dot--com.

**Comment by RaiMan** [comment]
no feedback
