### ISSUE TITLE
keyDown behaviour doesn't match that of documentation

### ISSUE THREAD

**Issue by fatuhoku** [RaiMan/SikuliNG#27]
http://sikulix-2014.readthedocs.io/en/latest/region.html#Region.keyDown reads

```
Parameters: | key\|list-of-keys – one or more keys (use the consts of class Key). A list of keys is a concatenation of several key constants using “+”.
-- | --
the number 1 if the operation could be performed and 0 if otherwise.
```

... but `keyDown(" ")` does not hold the key down. It just presses it and the program terminates.

Clarity around this please?

**Comment by RaiMan** [comment]
no longer relevant
