### ISSUE TITLE
Feature request: ocr-find a given text in a given region (region parameter, string parameter) and return the region where it was found

### ISSUE THREAD

**Issue by Markus-1974** [RaiMan/SikuliNG#32]
I think it would be very useful to have a function to search for a text in a region:

something like
Region region searchArea = ... // region of a dialog box or a listview
String textToSearch = "12345"; // e.g. article number
Region region = ocrfind(searchArea, textToSearch);

My idea would be the following use cases:
- in a sikulix-test, you could check if an application returns the correct result string
- when doing application-automization, you could click on an item in a list-box that contains a text.

My idea how it could be implemented (maybe there are better ideas to do this): 
Get a screenshot of the searchArea, do ocr on the screenshot, find text and its character positions, return the smallest region containing the text. Optionally you could use a levenstein algorithm to find a similar text in the ocr result.

What do you think about this idea?

**Comment by RaiMan** [comment]
available in SikuliX version 2.0.0
